<?xml version="1.0" encoding="utf-8"?><Database Name="BanHang" Class="DataQLBHDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI\LEMINHQUANG;Initial Catalog=BanHang;Integrated Security=True" SettingsObjectName="BanHang.Properties.Settings" SettingsPropertyName="BanHangConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTHD" Member="CTHDs">
    <Type Name="CTHD">
      <Column Name="MaHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_CTHD" Member="HoaDon" ThisKey="MaHD" OtherKey="MaHD" Type="HoaDon" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Menu_CTHD" Member="Menu" ThisKey="MaSP" OtherKey="MaSP" Type="Menu" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GioHang" Member="GioHangs">
    <Type Name="GioHang">
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Loai" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_GioHang" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Menu_GioHang" Member="Menu" ThisKey="MaSP" OtherKey="MaSP" Type="Menu" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NgayBan" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_CTHD" Member="CTHDs" ThisKey="MaHD" OtherKey="MaHD" Type="CTHD" />
      <Association Name="HoaDon_TrangThai" Member="TrangThai" ThisKey="MaHD" OtherKey="MaHD" Type="TrangThai" Cardinality="One" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoDT" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_GioHang" Member="GioHangs" ThisKey="MaKH" OtherKey="MaKH" Type="GioHang" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="MaKH" OtherKey="MaKH" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Loai" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Menu_CTHD" Member="CTHDs" ThisKey="MaSP" OtherKey="MaSP" Type="CTHD" />
      <Association Name="Menu_GioHang" Member="GioHangs" ThisKey="MaSP" OtherKey="MaSP" Type="GioHang" />
    </Type>
  </Table>
  <Table Name="dbo.TrangThai" Member="TrangThais">
    <Type Name="TrangThai">
      <Column Name="MaHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Association Name="HoaDon_TrangThai" Member="HoaDon" ThisKey="MaHD" OtherKey="MaHD" Type="HoaDon" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>